{
 "title": "Requests",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "get_requests_per_minute_rpm{job=\"jwt-pizza-service\"}",
     "legendFormat": "Get/"
    },
    {
     "expr": "post_requests_per_minute_rpm{job=\"jwt-pizza-service\"}",
     "legendFormat": "POST/"
    },
    {
     "expr": "put_requests_per_minute_rpm{job=\"jwt-pizza-service\"}",
     "legendFormat": "PUT/"
    },
    {
     "expr": "delete_requests_per_minute_rpm{job=\"jwt-pizza-service\"}",
     "legendFormat": "Delete/"
    },
    {
     "expr": "requests_per_minute_rpm{job=\"jwt-pizza-service\"}",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Pizza Rev Bitcoin/Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "pizza_revenue_per_minute_BTC_per_min{job=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza Rev bitcoin"
    }
   ]
  },
  {
   "title": "Pizza Sold",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "pizza_sales_per_minute_pizzas_per_min{job=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza Sold"
    },
    {
     "expr": "pizza_failures_per_minute_per_min{job=\"jwt-pizza-service\"}",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Auth Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "auth_success_per_minute_rpm{job=\"jwt-pizza-service\"}",
     "legendFormat": "Successful Login"
    },
    {
     "expr": "auth_failure_per_minute_rpm{job=\"jwt-pizza-service\"}",
     "legendFormat": "Failed Login"
    }
   ]
  },
  {
   "title": "Active Users/ 15mins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "active_users{job=\"jwt-pizza-service\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "request_latency_milliseconds{job=\"jwt-pizza-service\"}",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Pizza Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "pizza_order_latency_avg_milliseconds{job=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza Latency"
    }
   ]
  },
  {
   "title": "CPU & Memory %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "cpu_percent{job=\"jwt-pizza-service\"}",
     "legendFormat": "CPU %"
    },
    {
     "expr": "memory_percent{job=\"jwt-pizza-service\"}",
     "legendFormat": "Memory %"
    }
   ]
  }
 ]
}